syntax = "proto3";

option java_package = "Networking.Protobuf"; 
option java_outer_classname = "BasketballProto"; 
option csharp_namespace = "BasketballTicketSystem.Networking.Protobuf";

message TeamDto {
    int32 team_id = 1;
    string name = 2;
}

message StadiumDto {
    int32 stadium_id = 1;
    string name = 2;
    int32 capacity = 3;
}

message CustomerDto {
    int32 customer_id = 1;
    string name = 2;
}

message MatchDto {
    int32 match_id = 1;
    TeamDto team_a = 2;      
    TeamDto team_b = 3;      
    StadiumDto stadium = 4;  
    int32 number_of_seats_available = 5;
    float ticket_price = 6;
}

message TicketDto {
    int32 ticket_id = 1;
    MatchDto match = 2;       
    CustomerDto customer = 3; 
    int32 number_of_seats = 4;
}

// SPECIFIC REQUESTS (Client -> Server)

message LoginRequest {
    string username = 1;
    string password = 2;
}

message GetMatchesRequest {
    int32 min_seats = 1; 
}

message BuyTicketRequest {
    int32 match_id = 1;
    int32 customer_id = 2;
    int32 number_of_seats = 3;
}

// SPECIFIC RESPONSES (Server -> Client)

message LoginResponse {
    bool success = 1;
    string error_message = 2;
}

message GetMatchesResponse {
    repeated MatchDto matches = 1; 
}

message BuyTicketResponse {
    bool success = 1;
    string error_message = 2;
    TicketDto purchased_ticket = 3; 
}

message UpdateNotification {
    MatchDto updated_match = 1; 
}

// THE ENVELOPES (For Sockets)

message Request {
    oneof payload {
        LoginRequest login = 1;
        GetMatchesRequest get_matches = 2;
        BuyTicketRequest buy_ticket = 3;
    }
}

message Response {
    oneof payload {
        LoginResponse login = 1;
        GetMatchesResponse get_matches = 2;
        BuyTicketResponse buy_ticket = 3;
        UpdateNotification update = 4; 
    }
}